
import Header from '@/Components/Header/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import { Poppins } from 'next/font/google'
import Navbar from '@/Components/Navbar'
import MenuBar from '@/Components/MenuBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {/* <Navbar/>
        <MenuBar/> */}
        
        {children}
   
      </body>
    </html>
  )
}
